In [0]:
# Import torch and other required modules
import torch

#  Machine Learning: Pytorch Functions

### Introduction

Pytorch is a machine learning frameworks used for purposes such as Natural language Processing, computer vision among others. Pytorch has a huge library of functions but my study today will focus on 5 functions which are:
- function 1-torch.unique()
- function 2-torch.prod()
- function 3-torch.norm()
- function 4-torch.median()
- function 5-torch.argmax()

## Function 1 - torch.unique ()

     return the unique element of the input tensor

In [0]:
# Example 1 - working tensor and type long array
input = torch.tensor([1, 3, 2, 3]  ,dtype=torch.long)
output = torch.unique(input)
output

tensor([1, 2, 3])

The input is printed in increasing order with no repetitive number.

In [0]:
# Example 2 - use of inverses_indices for torch unique

if Inverse_indices is true, there will ve an additional returned tensor(same shape as input) representing the indices for where elements in the original input map to in the output; otherwise, this function will only return a single tensor.

In [0]:
output, inverse_indices = torch.unique(
        torch.tensor([1, 3, 2, 3], dtype=torch.long), sorted=True, return_inverse=True)
output

inverse_indices

tensor([0, 2, 1, 2])

In [0]:
# Example 3 - breaking when the dtype is entered in unique 
input = torch.tensor([1, 3, 2, 3]  )
output = torch.unique(input, dtype=float)
output

TypeError: ignored

the unique tensor can be use to sort data in a tensor and avoid repetitive data.

## Function 2 - torch.prod()

Returns the product of all elements in the input tensor.

In [0]:
# Example 1 - torch.prod(input, dtype=None)
a = torch.randn(1, 3)
a
torch.prod(a)



tensor(0.0109)

In [0]:
# Example 2 - torch.prod(input, dim, keepdim=False, dtype=None)

a = torch.randn(4, 2)
a
torch.prod(a, 1)



tensor([ 0.8728, -1.2239,  0.0473, -0.0071])

Returns the product of each row of the input tensor in the given dimension dim.

## Function 3 - torch.norm()

Returns the matrix norm or vector norm of a given tensor.

In [0]:
# Example 1 
a = torch.arange(9, dtype= torch.float) - 4
b = a.reshape((3, 3))
torch.norm(a)
torch.norm(b)

torch.norm(a, float('inf'))

torch.norm(b, float('inf'))

c = torch.tensor([[ 1, 2, 3],[-1, 1, 4]] , dtype= torch.float)
torch.norm(c, dim=0)
torch.norm(c, dim=1)

torch.norm(c, p=1, dim=1)
d = torch.arange(8, dtype= torch.float).reshape(2,2,2)
torch.norm(d, dim=(1,2))

torch.norm(d[0, :, :]), torch.norm(d[1, :, :])

(tensor(3.7417), tensor(11.2250))

## Function 4 - torch.median()

Returns the median value of all elements in the input tensor.

In [13]:
# Example 1 
a = torch.randn(1, 3)

torch.median(a)


tensor(0.2540)

Knowing the median is very important in machine learning and it can be use to know the middle average speed of a car that has the data store in a pytorch array

## Function 5 - torch.argmax()

Returns the indices of the maximum value of all elements in the input tensor.

In [0]:
# Example 1 
a = torch.randn(4, 4)
a

torch.argmax(a)

This allow the user to know the position of the higest number in a tensor. Therefore if we have different scales of song we can identify where the highest pitch is located.

## Conclusion

This notebook is a set of few pytorch function that I find particularly interesting because of their purpose related to predictions and sorting. I will encourage you to continue reading more about the documentation on the official website of Pytorch

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html


In [0]:
!pip install jovian --upgrade --quiet

In [0]:
import jovian

In [16]:
jovian.commit()

[jovian] Error: Failed to detect Jupyter notebook or Python script. Skipping..
